import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Anta, Saira } from "next/font/google";

// Load both fonts with custom subsets or weights
const anta = Anta({ subsets: ["latin"], weight: "400", variable: "--font-anta" });
const saira = Saira({ subsets: ["latin"], weight: ["400", "600"], variable: "--font-saira" });
import "./globals.css";


export const metadata: Metadata = {
  title: "Michael Buenrostro Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anta.variable} ${saira.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
