import "./globals.css";

import type { Metadata } from "next";
import { Anta, Saira } from "next/font/google";

const anta = Anta({ subsets: ["latin"], weight: "400", variable: "--font-anta" });
const saira = Saira({ subsets: ["latin"], weight: ["400", "600"], variable: "--font-saira" });


export const metadata: Metadata = {
  title: "Michael Buenrostro Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anta.variable} ${saira.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
